### ISSUE TITLE
refactor target interface

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#129]
@Tsym-or-Tysm as discussed, need to strip out the following methods:

```
	//basic info
	Type() TargettableType //type of target
	MaxHP() float64
	HP() float64

	//tags
	SetTag(key string, val int)
	GetTag(key string) int
	RemoveTag(key string)

	//target mods
	AddDefMod(key string, val float64, dur int)
	AddResMod(key string, val ResistMod)
	RemoveResMod(key string)
	RemoveDefMod(key string)
	HasDefMod(key string) bool
	HasResMod(key string) bool

```

so we're left with just
```

	Index() int            //should correspond to index
	SetIndex(ind int)      //update the current index

	//collision detection
	Shape() Shape

	//attacks
	Attack(*AttackEvent) (float64, bool)

	//reaction/aura stuff
	Tick()
	AuraContains(...EleType) bool
	AuraType() EleType

	//getting rid of
	Kill()
```

and instead any method that needs to know what type it is can either use a type switch (which seems to be just as fast as calling Type()) and cast it to the appropriate type

the stuff stripped out can be enemy specific

**Comment by Tsym-or-Tysm** [comment]
Something else that I think we should add when we do this refactor is enemy/target names, since it'll be useful especially when we start adding more/different types of enemies/entities.

This may or may not be prompted because I saw a lot of debug messages relating to a brand new target in configs that confused me until I realized that it was just the newly added Guoba lol.

**Comment by srliao** [comment]
done
