### ISSUE TITLE
alhaitham chisel mirrors issues

### ISSUE THREAD

**Issue by vhtNov17** [genshinsim/gcsim#1503]
his mirrors icd has a problem and
he only releases 1 mirror attack WAVE when he has 1 mirror, it supposed to be 2 waves

**Comment by k0l11** [comment]
Please provide a viewer link to an example sim and point out specifically what is wrong.

**Comment by vhtNov17** [comment]
u should try running this. his chisel mirror doesnt spread frequently as it should be. it doesnt spread until the 7th hit in reality it procs spread every 2 hits
https://gcsim.app/sh/1b1c24e2-36ee-470e-b5eb-d43e95b548c1

**Comment by k0l11** [comment]
His mirror elemental application ICD is correct (12s timer, alternating 1 0 1 0 ... hit rule) and it is correct that when he has 1 Mirror he only releases 1 Mirror attack wave (see his talent description/scaling or gameplay). The reason why you experience such few spreads, is because the other team members constantly react with the quicken aura and the Mirror elemental application happens to line up in such a way that it applies dendro when there is no quicken aura on the enemy (see the Sample tab with only the action, character, damage and element categories turned on). This is due to timings, you can try adding/removing actions to observe if you get more spreads/dps. As far as I can tell, nothing is bugged here.

**Comment by vhtNov17** [comment]
when he has 1 mirror he deals 1 slash BUT after 1.8s later he deals another slash (aka WAVE) until his mirrors disappear. 
3 mirrors 2 wave 3 hits
2 mirrors 2 wave 2 hits
1 mirror 2 wave 1 hit
however the simulator only shows 1 wave

**Comment by k0l11** [comment]
That's not how his mirrors work. If you proc a 1/2/3 Mirror wave, then there are only 1/2/3 hit(s) in a single wave. Please check against ingame/video footage if you don't believe me.

**Comment by vhtNov17** [comment]
im not talking about hit im talking about waves. all his mirrors send out 2 waves however the simulator only gives him 1 wave when he has 1 mirror

**Comment by vhtNov17** [comment]
u can try "attack:3,dash" 2 times when he has 1 mirror. u only see 1 wave

**Comment by k0l11** [comment]
Here's a config with the actions you gave me: https://gcsim.app/sh/F9DhJTH9NQz8
As you can see he gets 2x 3 Mirror waves, 2x 2 Mirrow waves, 1x 1 Mirror waves. What you're saying doesn't line up with what I see here and it all seems not bugged to me.

**Comment by k0l11** [comment]
This is because the sim is faster than 99% of humans without adding in waits, so your last N3D ends before the proc cooldown is up. Here's an example where I achieved what you described by adding a `wait(40);`: https://gcsim.app/sh/DcTzTcmDf7pQ

**Comment by vhtNov17** [comment]
okay so everything works like intended right? i can be wrong but atleast i figured things out. thank for explaining things to me and sr for wasting ur time. btw "skill[hold=1], high_plunge" make the sim stop working. is this normal?

**Comment by k0l11** [comment]
Yes, everything works as intended. Don't worry about wasting my time, at least we were able to clear it up. Yes, it's normal that `high_plunge` doesn't work, only `low_plunge` is legal.
