### ISSUE TITLE
source dps graph not showing on shares

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#1519]
![image](https://github.com/genshinsim/gcsim/assets/906239/2f1a979e-ff16-43df-9cc6-d09b17eac06d)

I probably missed some settings on backend protos

**Comment by unleashurgeek** [comment]
We were not going to be creating a release until tomorrow... 
![image](https://github.com/genshinsim/gcsim/assets/2059811/243f9398-bcb1-4272-b012-5c7c015fd5b7)


This is the expected behavior for any new deployment, new fields will not be populated until backend has the latest version where it is aware of such field. Since backend is deployed with latest commit, share links now can have this field populated: https://gcsim.app/sh/KkgwM9KjHW8J

**Comment by srliao** [comment]
> We were not going to be creating a release until tomorrow... ![image](https://user-images.githubusercontent.com/2059811/252121313-243f9398-bcb1-4272-b012-5c7c015fd5b7.png)

Oops my bad. I'll create a GitHub discussion asking next time before pushing any buttons.

> This is the expected behavior for any new deployment, new fields will not be populated until backend has the latest version where it is aware of such field. Since backend is deployed with latest commit, share links now can have this field populated: https://gcsim.app/sh/KkgwM9KjHW8J

Can confirm. I clicked share button too early I guess before backend deploy finished
