### ISSUE TITLE
Change Artifacts to Enums

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#162]
Otherwise site UI pictures are busted for everyone using the cmd.

![image](https://user-images.githubusercontent.com/84653157/149068719-6d41fd84-4053-464e-8bc7-4a66bda28a80.png)

**Comment by srliao** [comment]
Jotting down some thoughts on this:

- Rather than the intertwined system we have with characters with keys in `core` etc... (which I don't really like), I would prefer that all information relating to each artifact set is contained in the artifact set it self (separation of concern)
- One way maybe to achieve this is to have artifacts register both a `key` and also various names the set can be recognized/known by with the `core`. The `core` can then respond back with an integer key to which this set will be known by. This key is unique to that set for that one specific run.
- Need to think about the pros and cons of this

**Comment by srliao** [comment]
done in `next`
