### ISSUE TITLE
Gorou's Buff durations/snapshots

### ISSUE THREAD

**Issue by Aftermathrar** [genshinsim/gcsim#211]
was testing out some gorou teams and noticed that his buffs seem to have some issues currently:
- the c6 buff is being included in snapshots, when it should behave similarly to sara c6 and not snapshot
- the A1/C6 durations are separate from the main E/Q field buffs and are on a strict 12s timer starting from around frame 15-30 (haven't exactly narrowed it down with testing)
- the Flat Def/Geo DMG% ticks like bennet's field does. i'm not too sure on the timing, but it seems like it's close to every 60 frames starting on about frame 60

[Sample viewer file with above issues.](https://viewer.gcsim.app/share/HM245qPmPgqSNFZQWv8Mn) I'm not too sure if I'm reading the status application correctly.

**Comment by Aftermathrar** [comment]
Gorou's Burst duration seems to be extended for an abnormal amount of time, as well. The c2 max extension should be 3 seconds (180 frames), but in the viewer file it's active more than 18 seconds later.

**Comment by Aftermathrar** [comment]
I was incorrect about Gorou's C6 in the first post. I didn't realize that the buff was applied to the whole party for its duration, so what I was seeing wasn't it snapshotting, but being active as it's supposed to be. I would still double-check the duration on it to be sure it's not getting extended.

**Comment by Tsym-or-Tysm** [comment]
C6 was actually incorrectly snapshotting, which is fixed in #223. 

I checked and Gorou E/Q buffs are indeed ticking every 59 frames in the code and in your viewer file so I think that's fine.

I did not address A1/C6 timer (let us know if you investigated the exact timing, otherwise I'm just going to split the difference at 22 frames and it'll probably be good enough) or the burst extension bug that you see yet (haven't had time to investigate since the code seems ok at a glance)

**Comment by shizukayuki** [comment]
C2 should be fixed in #542, other than timing issues i don't see anything wrong.

**Comment by k0l11** [comment]
buff timings should be fixed by #677
