### ISSUE TITLE
Initialized Mods Are in Wrong Column in Debug

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#293]
![image](https://user-images.githubusercontent.com/84653157/154829224-e0db5818-9073-4d7f-8d3b-713ea22fd217.png)

Issue occurs because some mods are initialized before each character gets their character index, so a lot of them group up in character index 0.

**Comment by srliao** [comment]
So the fix for this is for all the weapons/artifact/etc.. to add their mods into an event subscription for OnInitialize, which gets called after characters are initialized like this here: https://github.com/genshinsim/gcsim/blob/076cf0bf8e6ba9f5d3c80e3a9b992251d456e6d0/internal/artifacts/huskofopulentdreams/huskofopulentdreams.go#L81

**Comment by Tsym-or-Tysm** [comment]
Sounds good to me. Given how this design pattern needs to be replaced a million times throughout the code, we should instead add a function that handles this explicitly I think as part of a broader mod refactor (whenever we get around to #118 )

Something like `AddModOnInit` or whatever.

**Comment by srliao** [comment]
fix merged to main in #350
