### ISSUE TITLE
Consistent Way to Handle Midair Plunges for All Characters

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#41]
Currently, midair plunge hits are handled as an option in the high plunge and low plunge attack actions for each character separately. At some point in the future, we may want to set up a consistent framework for this across all characters.

If we decide to keep using options, then this should be flagged in the documentation/readme/wiki.

**Comment by srliao** [comment]
So my understanding is that this is the plunge hit if you land right on top of a target.

Since we have hitboxes now we can implement this as just a small pin point attack. We might need to add a rand to the x,y of the attack of some sort to simulate we cant always land plunge perflect?

**Comment by k0l11** [comment]
Closing as wontfix, because there's no real practical use for this: 
- limited number of chars with collision plunge in sim (amount duplicated logic is low)
- collision plunge attacktag/icd/... may be the same between chars for now, but that could change in the future so I think it's better to keep it separate
