### ISSUE TITLE
a problem of klee

### ISSUE THREAD

**Issue by kawayiYokami** [genshinsim/gcsim#442]
klee's E skill   :  ①Jumpy Dumpty should hit 3 times & ②Jumpy Dumpty Mine Hit should hit at least 6(sometimes 8) times

**Comment by srliao** [comment]
hi

thanks for the issue.

right now this is actually set via a param. so for example:

`skill[bounce=3,mine=8]` will result in jumpty dumpty bounce hitting 3 times and mine hitting 6 times

it's not quite ideal but because there's no physics in gcsim this is the best idea i got for now. if you have better ideas feel free to leave a comment.

**Comment by kawayiYokami** [comment]
I've been learning how to write from other people's databases. I haven't found this. It's very useful

**Comment by kawayiYokami** [comment]
thank you so much！！！
